name: SyncFromUpstream

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/OlivOS-Team/OlivaDiceCore.git || true
          git fetch upstream

      - name: Merge upstream/main
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push changes to fork
        env:
          FORK_TOKEN: ${{ secrets.FORK_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${FORK_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
